version: "3.9"

services:
  game_db:
    image: postgres:18-alpine
    container_name: game_database
    environment:
      POSTGRES_DB: game_db
      POSTGRES_USER: user_db
      POSTGRES_PASSWORD: password_db
    volumes:
      - ./game:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"

  users_db:
    image: postgres:18-alpine
    container_name: users_database
    environment:
      POSTGRES_DB: users_db
      POSTGRES_USER: user_db
      POSTGRES_PASSWORD: password_db
    volumes:
      - ./user:/docker-entrypoint-initdb.d
    ports:
      - "5433:5432"
